### ISSUE TITLE
Current delta between SymbiFlow/yosys and YosysHQ/Yosys in master+wip

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/yosys#43]
- [ ] #41 - https://github.com/SymbiFlow/yosys/tree/attributes-on-parameters - Enable attributes on parameters.
 - [ ] #40 -https://github.com/SymbiFlow/yosys/tree/carry-rework - Use CARRY4 rather than multiple CARRY objects.
 - [ ] #39 - https://github.com/SymbiFlow/yosys/tree/disable-ramb36e1 - Disable RAMB36E1 output
 - [ ] #38 - https://github.com/SymbiFlow/yosys/tree/disable-srl16  - Disable SRL16 output

**Comment by mithro** [comment]
FYI - @eddiehung
